[package]
org = "himeshdevinda"
name = "ballerina_asgardeo_events"
version = "0.1.0"
distribution = "2201.4.1"

[build-options]
observabilityIncluded = true

[[dependencies]]
org = "ballerina/websub"
name = "http"
version = "2.10.0"
